### ISSUE TITLE
suggestion - add reverse sort order option

### ISSUE THREAD

**Issue by jakewarren** [acarl005/ls-go#1]
I often use the reverse sorting option with `ls`, particularly when sorting by time. I am not sure what flags would be appropriate here since `-r` and `-R` are already in use.

**Comment by acarl005** [comment]
Sounds like a useful addition. Perhaps `-B` for backwards? Would accept PR for this. Or I'll add myself at my next convenience.

**Comment by sfluor** [comment]
Hello ! I would be very happy to do it as a first contribution to a project 😄 .

**Comment by acarl005** [comment]
`--backwards` option is accepted. As a minor tweak I decided to have the dirs remain at the top, but the sort order is still being reversed. Thanks again!
